# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-03 17:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('VirtualTour', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='images_graph',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.IntegerField()),
                ('node_a', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='node_a', to='VirtualTour.images')),
                ('node_b', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='node_b', to='VirtualTour.images')),
            ],
        ),
    ]
