# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-15 17:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('VirtualTour', '0003_remove_images_graph_cost'),
    ]

    operations = [
        migrations.CreateModel(
            name='story',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descrp', models.CharField(max_length=2000)),
                ('heading', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='heading', to='VirtualTour.images')),
            ],
        ),
    ]
