# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-15 20:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('VirtualTour', '0004_story'),
    ]

    operations = [
        migrations.CreateModel(
            name='dignitory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descrp', models.CharField(max_length=20000)),
                ('pano1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pano1', to='VirtualTour.images')),
            ],
        ),
        migrations.CreateModel(
            name='general_path',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descrp', models.CharField(max_length=20000)),
                ('heading', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='heading', to='VirtualTour.images')),
            ],
        ),
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descrp', models.CharField(max_length=20000)),
                ('pano', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pano', to='VirtualTour.images')),
            ],
        ),
        migrations.RemoveField(
            model_name='story',
            name='heading',
        ),
        migrations.DeleteModel(
            name='story',
        ),
    ]
