# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-17 13:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VirtualTour', '0005_auto_20170615_2043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dignitory',
            name='pano1',
        ),
        migrations.RemoveField(
            model_name='student',
            name='pano',
        ),
        migrations.AddField(
            model_name='general_path',
            name='type1',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='dignitory',
        ),
        migrations.DeleteModel(
            name='student',
        ),
    ]
