# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-17 13:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VirtualTour', '0006_auto_20170617_1325'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='general_path',
            name='type1',
        ),
    ]
