# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-18 07:28
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VirtualTour', '0007_remove_general_path_type1'),
    ]

    operations = [
        migrations.AddField(
            model_name='general_path',
            name='qty',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(3), django.core.validators.MinValueValidator(0)]),
        ),
    ]
