# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-18 07:30
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VirtualTour', '0008_general_path_qty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='general_path',
            name='qty',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(2), django.core.validators.MinValueValidator(0)]),
        ),
    ]
