# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-28 05:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VirtualTour', '0012_auto_20170627_1058'),
    ]

    operations = [
        migrations.AddField(
            model_name='general_path',
            name='title',
            field=models.CharField(default='', max_length=200),
        ),
    ]
